- hosts: elk
  become: True
  tasks:
    - name: get elasticsearch enrolment token
      community.docker.docker_container_exec:
        container: elasticsearch 
        command: /bin/bash -c "/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana"
      register: result
    - debug:
        var: result.stdout
    tags: [elastic, never]
- hosts: elk
  become: True
  tasks:
    - name: get kibana verification code
      community.docker.docker_container_exec:
        container: kibana
        command: /bin/bash -c "kibana-verification-code"
      register: result
    - debug:
        var: result.stdout
    tags: [kibana, never]
